import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";

const app = express();
const PORT = 3000;

app.use(express.json());

// Lazy-initialized GoogleGenAI client helper
let aiClient: GoogleGenAI | null = null;
function getGeminiClient(): GoogleGenAI {
  if (!aiClient) {
    const key = process.env.GEMINI_API_KEY;
    if (!key || key === "MY_GEMINI_API_KEY") {
      throw new Error("GEMINI_API_KEY is not configured in environment variables. Please configure it in the Secrets panel in the AI Studio UI.");
    }
    aiClient = new GoogleGenAI({
      apiKey: key,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        }
      }
    });
  }
  return aiClient;
}

// REST API for dynamic agent analysis using server-side Gemini SDK
app.post("/api/gemini/analyze", async (req, res) => {
  try {
    const { moduleType, context, prompt } = req.body;
    
    // Check if key exists. If not, return elegant simulated fallback so it's fully secure and non-blocking!
    const key = process.env.GEMINI_API_KEY;
    if (!key || key === "MY_GEMINI_API_KEY") {
      // Return high-quality, simulated business-grade analysis representing Casper Atlas' native AI agents
      const simulatedResponses: Record<string, string> = {
        marketplace: `### [Simulated Casper Atlas Marketplace Analytics]
**Agent Name**: Casper Yield Harvester (v1.4)
**Trust Score**: 99.4/100 (Cryptographically Audited)
**Revenue Realized**: 482,501 CSPR
**Core Analysis**: Recommended for active treasury pools looking to route liquid funds through Casper's automated market maker pairs. The agent exhibits high historic uptime and minimal transaction execution slip in low-liquidity conditions. Configured for x402 micropayment streaming at 0.05 CSPR per state assertion.`,
        defi: `### [Simulated Casper DeFi Portfolio Optimization Report]
**Optimized Yield Target**: 12.8% APY
**Risk Metrics**: Beta 0.42 | Maximum Drawdown 2.1%
**Simulated Allocation**:
- **CSPR Staking Node #04**: 60% (Staked via CSPR.click Auth delegator)
- **CSPR/USD Liquidity Pool (CasperSwap)**: 30% (Hedged using dynamic delta-neutral trigger)
- **Liquid Reserve (x402 Micropayment Buffer)**: 10%
**Agent Directive**: Ready to authorize delegation requests on Odra contracts.`,
        rwa: `### [Simulated Casper RWA Intelligence Attestation]
**Asset Identified**: Green Standard Carbon Credit Pool (RWA-C08)
**Total Pool Represented**: $1,250,000 USD
**Provider**: EarthRegistry Inc.
**Casper Verification State**: **VERIFIED (Block #4,851,202)**
**Confidence Score**: 98.6%
**Risk Score**: Low-Medium (A-)
**Attestation Hash**: \`c2f08a98bcff613...0951bd\`
**Verification Summary**: Attestation signed securely by compliance swarm agent using decentralized oracle feed. Data points verified conform to Gold Standard V2 methods. Verified against physical Registry metadata.`,
        governance: `### [Simulated Governance Swarm Consensus Report]
**Proposal Title**: Treasury Allocation #401: Fund Developer Guild Agent
**Swarm Poll Results**:
- **Risk Agent**: APPROVED (Impact score 8.5/10)
- **Treasury Agent**: APPROVED (Budget is within expected Q3 limits)
- **Economic Agent**: ABSTAIN (Suggests locking CSPR in a 6-month bond instead of liquid emission)
- **Legal Agent**: APPROVED (Compliant with Casper Network v2 legal guidelines)
- **Community Agent**: APPROVED (94% social trust alignment)
**Final Recommendation**: Swarm delivers consensus **APPROVED** (4-0-1). Proposal state submitted to Casper Smart Contract.`,
        contract: `// CODE GENERATED BY CASPER ATLAS AGENT ECONOMIC ORACLE (SIMULATED)
// Framework: Odra Smart Contract Framework (Rust)
// Target: Casper Network WASM Runtime

use odra::prelude::*;
use odra::{Variable, Mapping, Event};

#[odra::module]
pub struct CasperAgentRegistry {
    agents: Mapping<Address, AgentProfile>,
    fee_numerator: Variable<u32>,
    owner: Variable<Address>,
}

#[derive(Clone, PartialEq, Debug, odra::types::BorshSerialize, odra::types::BorshDeserialize)]
pub struct AgentProfile {
    pub name: String,
    pub trust_score: u8,
    pub reputation_earned: u64,
    pub micro_pay_rate: Balance,
    pub is_active: bool,
}

#[odra::module]
impl CasperAgentRegistry {
    #[odra::initializer]
    pub fn init(&mut self, fee: u32) {
        let caller = self.env().caller();
        self.owner.set(caller);
        self.fee_numerator.set(fee);
    }

    pub fn register_agent(&mut self, name: String, pay_rate: Balance) {
        let caller = self.env().caller();
        let profile = AgentProfile {
            name,
            trust_score: 100,
            reputation_earned: 0,
            micro_pay_rate: pay_rate,
            is_active: true,
        };
        self.agents.set(&caller, profile);
        self.env().emit_event(AgentRegistered { address: caller });
    }
}`
      };
      
      const customResponse = simulatedResponses[moduleType] || `### [Simulated Multi-Agent Consensus Insight]
**Context**: ${context || "General Intelligent Query"}
**Agent Insights**: Multi-Agent execution loop ran successfully on Casper Devnet. Complete. Note: To activate real-time live Gemini AI reasoning, configure the GEMINI_API_KEY in the Secrets panel.`;
      
      return res.json({ text: customResponse, simulated: true });
    }

    const ai = getGeminiClient();
    const systemPrompt = `You are the primary decentralized AI reasoning engine for Casper Atlas: The Operating System for the Agent Economy on the Casper Network.
Your goal is to provide highly precise, expert fintech analysis, real-life-styled Casper Odra Smart Contracts, risk assessment scoring, or agent logic.
Acknowledge technical details of the Casper blockchain, such as fast finality, low execution fees, Odra Rust Framework, CSPR.click SDK, x402 micropayments, and CSPR.cloud API.
Deliver structural responses in beautiful, professional clean Markdown with specific numbers, hashes, or code metrics suited to the Bloomberg/Palantir aesthetic. Keep it concise, high density, and action-oriented.`;

    const finalPrompt = `${prompt}\n\nContext block: ${JSON.stringify(context)}`;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: finalPrompt,
      config: {
        systemInstruction: systemPrompt,
        temperature: 0.2, // robust and deterministic for fintech dashboard feel
      },
    });

    res.json({ text: response.text, simulated: false });
  } catch (error: any) {
    console.error("Gemini route error:", error);
    res.status(500).json({ error: error.message });
  }
});

// Endpoint for live real-time simulation feed details
app.get("/api/dashboard/stats", (req, res) => {
  res.json({
    activeAgents: 1422,
    agentEarnings: "3,842,504 CSPR",
    x402Transactions: 489512,
    assetsManaged: "$14,851,200 USD",
    governanceProposals: 87,
    rwaVerifications: 124,
    averageTrustScore: "96.4%",
    nodesSyncingState: "Healthy (100 Nodes)",
    lastBlock: 4851219,
    recentEvents: [
      { id: "e1", type: "x402_payment", message: "Agent 'Sentinel-04' received 12 CSPR micropayment from 'Arbitrageur-09'", timestamp: "Just now" },
      { id: "e2", type: "rwa_verified", message: "RWA swine registry ledger Attestation validated for Cargo Credit RWA-91", timestamp: "1m ago" },
      { id: "e3", type: "governance_debate", message: "Treasury Swarm consensus achieved on Proposal #118 with positive vote", timestamp: "3m ago" },
      { id: "e4", type: "reputation_increase", message: "Trust score for Agent 'YieldBot' raised to 99.8% after perfect block batch execution", timestamp: "5m ago" },
    ]
  });
});

// Serve health checking
app.get("/api/health", (req, res) => {
  res.json({ status: "ok" });
});

async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`[Casper Atlas Server] Running on http://localhost:${PORT}`);
  });
}

startServer();
